version: '3.5'

services:
  mongo:
    container_name: tmai_mongo
    image: mongo:4.4.2
    networks:
      - database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tmai
    ports:
      - "27017-27019:27017-27019"
    restart: unless-stopped

  mongo-express:
    container_name: tmai_mongo_express
    image: mongo-express:0.54
    networks:
      - database
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081
    restart: unless-stopped

  tmai-server:
    build: ./
    ports:
      - 3000:3000
    networks:
      - database
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://tmai:password@localhost:27017/tmai
    restart: unless-stopped

networks:
  database:
    driver: bridge

