export const JWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0Ijo0MTAyNDQ0ODAwLCJhdWQiOiJ0bWFpc2VydmVyIiwiaXNzIjoidG1haXNlcnZlciIsImVtYWlsIjoidGVzdEB0bWFpLmNvIn0.XtPblwXXi1QdIaZ0dCHN6Xwc8xjQ_1Grmd7Cra2KhKQ";
