name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Start the environment necessary to run test
        run: docker-compose -f docker-compose.yml up -d mongo && sleep 10

      - name: Test
        run: MONGODB_URL=mongodb://tmai:password@localhost:27017/tmai go test -v ./...

      - name: Shutting down test environment
        run: docker-compose -f docker-compose.yml kill && docker-compose -f docker-compose.yml rm -f
